# Generated by Django 3.0.3 on 2020-02-29 09:12

from django.db import migrations


def create_data(apps, schema_editor):
    student = apps.get_model('studentsapp', 'Student')
    student(name="Ashish S", email="msashish@gmail.com", document="7654567", phone="9990000000").save()
    student(name="Vikram M", email="iamvicky@gmail.com", document="1230000", phone="7770000000").save()
    student(name="Joe Silver", email="joe@email.com", document="22342342", phone="00000000").save()


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
